# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

# Only for Snow CLI, can override connection details as follows
#export SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD=""

default_connection_name = "default"
